Fail in test_titles of ironic-specs
When run tox to test, the error below appears:
...
dict(expect.items() + allowed.items())]

TypeError: unsupported operand type(s) for +:
'dict_items' and 'dict_items'
...

Change-Id: I54154927e08d04248301d4d29de1d88d13890c01
Closes-Bug: #1755169